// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8onMRJs4VTAkWtlx4-NEyyhWUU7ryDvc',
    appId: '1:282121006227:web:e84db9443a819684cc3166',
    messagingSenderId: '282121006227',
    projectId: 'gdsc-vikas',
    authDomain: 'gdsc-vikas.firebaseapp.com',
    storageBucket: 'gdsc-vikas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsxNh_PC091fojfo8nSyZeyB3k0ZBpOFw',
    appId: '1:282121006227:android:6ca437652aa9eef5cc3166',
    messagingSenderId: '282121006227',
    projectId: 'gdsc-vikas',
    storageBucket: 'gdsc-vikas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-9s_BbQ6sba_b1DiSiK3eY5jTIIfYWI',
    appId: '1:282121006227:ios:e8c2bb40b90ea7c6cc3166',
    messagingSenderId: '282121006227',
    projectId: 'gdsc-vikas',
    storageBucket: 'gdsc-vikas.appspot.com',
    iosClientId:
        '282121006227-tp9optu4ldf2r5d0ri9spjnskth9hkmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vikasGdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-9s_BbQ6sba_b1DiSiK3eY5jTIIfYWI',
    appId: '1:282121006227:ios:9530d5527b01944ecc3166',
    messagingSenderId: '282121006227',
    projectId: 'gdsc-vikas',
    storageBucket: 'gdsc-vikas.appspot.com',
    iosClientId:
        '282121006227-guttpsqirdgrklg6iupgblfkmr5s7t6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vikasGdsc.RunnerTests',
  );
}
